apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cups-psp
  namespace: default
  annotations:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cups-psp
subjects:
- kind: ServiceAccount
  name: default
