apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  annotations:
  name: cups-psp
  namespace: default
rules:
- apiGroups:
  - policy
  resourceNames:
  - privileged-cups
  resources:
  - podsecuritypolicies
  verbs:
  - use
